### ISSUE TITLE
iOS app build failure

### ISSUE THREAD

**Issue by paraspathak** [nicobargit/TrafficSignalDetection#1]
The iOS app is having build failure and cannot find `SignalDetectionAppiOS/ObjectDetection/Model/notquantizedmob.tflite` as well as 
`SignalDetectionAppiOS/ObjectDetection/Model/notquantizedinc.tflite,` 
the coco zipped model also only has a `detect.tflite` file. 
Are these the models that need to be trained again or are they missing?

**Comment by nicobar97** [comment]
Yes, the coco ones are the models that need to be trained with fine tuning on the data set. I can provide you those file that I gitignored if you want to give a try without train the models. You can find them [here](https://drive.google.com/open?id=1pIYxxg0VLJd-JzMOrVqv5X6sJGPW5UOy)
And keep that in mind I made the gui only for iPhone X,XS and 11 Pro phones. 
I've updated the readme with this link too.
